import csv
import shutil
import sys

def process_report(report_path):
    with open(report_path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row['Action'] == 'MOVE':
                shutil.move(row['CurrentPath'], row['TargetPath'])
            elif row['Action'] == 'CREATE':
                with open(row['TargetPath'], 'w') as new_file:
                    new_file.write("# Auto-generated by Slick AI\n")

if __name__ == "__main__":
    process_report(sys.argv[1])
